// apps/web/src/routes/blogs/+page.svelte
<script lang="ts">
  import { Card } from '@binoy/ui';

  function getFormattedDate(publishedAt: string) {
    return new Date(publishedAt).toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    });
  }

  function getFormattedReadingTime(readingTime: number) {
    return `${readingTime} min read`;
  }

  export let data;
</script>

<svelte:head>
  <title>Blogs - Binoy Patel</title>
</svelte:head>

<div class="container">
  {#each data.blogs as blog}
    <Card className="my-10 py-10 px-10 first:mt-0">
      <a href={`/blogs/${blog.slug.current}`}>
        <h1 class="text-xl font-bold">{blog.title}</h1>
      </a>
      <h4 class="mt-2">
        {getFormattedDate(blog.publishedAt)} - {getFormattedReadingTime(blog.readingTime)}
      </h4>
      <p class="mt-4 text-lg">{blog.excerpt}</p>
    </Card>
  {/each}
</div>

// apps/home/pages/blogs.tsx
import { Card } from "@binoy14/ui";
import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { GetBlogs, getBlogs } from "../utils/groq/getBlogs";
import { sanityClient } from "../utils/sanityClientCdn";

interface Props {
  pages: GetBlogs;
}

const BlogsPage: NextPage<Props> = ({ pages }) => {
  return (
    <>
      <Head>
        <title>Blogs - Binoy Patel</title>
      </Head>
      <div className="container">
        {pages.map((page) => {
          const formattedDate = new Date(page.publishedAt).toLocaleDateString("en-US", {
            month: "long",
            day: "numeric",
            year: "numeric",
          });

          const formattedReadingTime = `${page.readingTime} min read`;

          return (
            <Card key={page.title} className="my-10 py-10 px-10 first:mt-0">
              <Link href={`/blogs/${page.slug.current}`}>
                <h1 className="text-xl font-bold">{page.title}</h1>
              </Link>
              <h4 className="mt-2">
                {formattedDate} - {formattedReadingTime}
              </h4>
              <p className="mt-4 text-lg">{page.excerpt}</p>
            </Card>
          );
        })}
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const blogs = await sanityClient.fetch<GetBlogs>(getBlogs);

  return {
    props: {
      pages: blogs,
    },
  };
};

export default BlogsPage;
