// apps/home/pages/contact.tsx
import { Card } from "@binoy14/ui";
import { GetStaticProps, NextPage } from "next";
import React from "react";
import { FaGithub, FaLinkedin, FaTwitter, FaYoutube } from "react-icons/fa";
import { MdEmail } from "react-icons/md";

import { GetContacts, getContacts } from "../utils/groq/getContacts";
import { sanityClient } from "../utils/sanityClientCdn";

const iconMap = {
  Twitter: FaTwitter,
  Youtube: FaYoutube,
  Email: MdEmail,
  Github: FaGithub,
  Linkedin: FaLinkedin,
} as const;

interface Props {
  contacts: GetContacts;
}

const ContactPage: NextPage<Props> = ({ contacts }) => {
  return (
    <div className="container">
      <Card>
        <h1 className="text-2xl font-bold">Say Hello!</h1>
        <div className="my-10 flex flex-wrap justify-center">
          {contacts.map(({ link, title }) => {
            const Icon = iconMap[title as keyof typeof iconMap];
            if (Icon) {
              return (
                <a href={link} key={link} target="_blank" rel="noreferrer noopener" className="ml-8 mb-8 first:ml-0">
                  <Icon size={50} title={title} />
                </a>
              );
            }

            return null;
          })}
        </div>
      </Card>
    </div>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const contacts = await sanityClient.fetch<GetContacts>(getContacts);

  return {
    props: {
      contacts,
    },
  };
};

export default ContactPage;

// apps/web/src/routes/contact/+page.svelte
<script lang="ts">
  import { Card } from '@binoy/ui';
  import FaGithub from 'virtual:icons/fa/github';
  import FaLinkedin from 'virtual:icons/fa/linkedin';
  import FaTwitter from 'virtual:icons/fa/twitter';
  import FaYoutube from 'virtual:icons/fa/youtube';
  import MdEmail from 'virtual:icons/mdi/email';

  export const contactIcons = {
    Twitter: FaTwitter,
    Youtube: FaYoutube,
    Email: MdEmail,
    Github: FaGithub,
    Linkedin: FaLinkedin
  } as const;

  function getIcon(title: string) {
    return contactIcons[title as keyof typeof contactIcons];
  }

  export let data;
</script>

<div class="container">
  <Card>
    <h1 class="text-2xl font-bold">Say Hello!</h1>
    <div class="my-10 flex flex-wrap justify-center">
      {#each data.contacts as { link, title }}
        <a href={link} target="_blank" rel="noreferrer noopener" class="mb-8 ml-8 first:ml-0">
          <svelte:component this={getIcon(title)} class="h-11 w-11" />
        </a>
      {/each}
    </div>
  </Card>
</div>
