// apps/web/src/lib/Image.svelte
<script lang="ts">
  import type { SanityImageSource } from '@sanity/image-url/lib/types/types';
  import { imageBuilder } from './sanityClient';

  export let src: SanityImageSource | null;
  export let height: number;
  export let width: number;
  export let alt: string | undefined;
  export let className: string | undefined = '';

  export let imgComp: HTMLImageElement | null = null;
</script>

{#if src}
  <img
    {alt}
    bind:this={imgComp}
    loading="lazy"
    class={className}
    {height}
    {width}
    src={imageBuilder.image(src).width(width).quality(75).auto('format').url().toString()}
  />
{/if}

// apps/home/components/Image.tsx
import NextImage from "next/image";

import { imageBuilder } from "../utils/sanityClientCdn";

import type { SanityImageSource } from "@sanity/image-url/lib/types/types";
import type { ImageLoaderProps, ImageProps as NextImageProps } from "next/image";

interface ImageProps extends Omit<NextImageProps, "src"> {
  src?: SanityImageSource | null;
}

const sanityLoader = (sanitySrc: SanityImageSource, { width, quality = 75 }: ImageLoaderProps) => {
  return imageBuilder.image(sanitySrc).width(width).quality(quality).auto("format").url();
};

export const Image: React.FC<ImageProps> = ({ src, ...props }) => {
  const baseUrl = "https://cdn.sanity.io/images/";

  if (!src) return null;

  return (
    <NextImage
      loader={(p) => sanityLoader(src, p)}
      {...props}
      src={imageBuilder.image(src).url().toString().replace(baseUrl, "")}
    />
  );
};
